main: me.deceptions.reacttoit.Main
name: ReactToIt
version: 1.4
author: FXA
website: https://deceptions.me
description: A plugin to test your players reaction times and reward them.
depend: [Vault]

commands:
  react:
    description: Starts react.
permissions:
  react.start:
    description: Permission to use /react